apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      containers:
      - name: logstash
        image: quay.io/bookshout/logstash-beats:master
        imagePullPolicy: Always
        ports:
        - containerPort: 5044
          name: beats
          protocol: TCP
